spring:
  application:
    name: olineMall-auth
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: xy131427
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6390
      password: xy131427
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

mybatis:
  type-aliases-package: com.project.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.project.repository: debug
